USE tempdb;
GO

CREATE TABLE Contas
(
	id INT PRIMARY KEY,
	saldo DECIMAL(10,2) CHECK (saldo >= 0)
);

INSERT INTO Contas VALUES 
(1, 1000.00),
(2, 500.00);
GO

-- EXEMPLO TRANSAÇÃO
BEGIN TRANSACTION;
	UPDATE Contas SET saldo = - 200 WHERE id = 1;

	-- FORCING MISTAKE
	UPDATE Contas SET saldo = - 800 WHERE id =2;
ROLLBACK TRANSACTION;

-- VISUALIZAÇÃO RESULTADO
SELECT * FROM Contas;