CREATE DATABASE PizzariaDB;
GO

USE PizzariaDB;
GO

CREATE TABLE Clentes
(
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	telefone VARCHAR(20) NOT NULL UNIQUE,
	endereco VARCHAR(255) NULL
);
GO